### PR TITLE
Fix typo in CliWrapCommandExtensions

### PR DESCRIPTION
**Pull request by Tyrrrz**

### CODE REVIEW

**Comment by alexyakunin** [comment]
Thanks, @Tyrrrz  - just noticed this is the first external PR to this repo :)

**Comment by alexyakunin** [comment]
@vchirikov FYI -- maybe the same issue is in some other of our repos.

**Comment by alexyakunin** [comment]
@Tyrrrz FYI I added you "Credits" section here: https://github.com/servicetitan/Stl.Fusion/blob/master/docs/README.md - hopefully that's ok :)

**Comment by Tyrrrz** [comment]
> @Tyrrrz FYI I added you "Credits" section here: https://github.com/servicetitan/Stl.Fusion/blob/master/docs/README.md - hopefully that's ok :)

Haha sure. Thanks!

**Pull request merged**
